import type { IconType } from "react-icons";
import {
  MdAdd,
  MdAddCircle,
  MdAnalytics,
  MdArchitecture,
  MdArrowRightAlt,
  MdAutoAwesome,
  MdAutoGraph,
  MdAutoStories,
  MdBolt,
  MdCalendarToday,
  MdCancelPresentation,
  MdChevronRight,
  MdDashboard,
  MdDelete,
  MdDownload,
  MdEdit,
  MdEditNote,
  MdGridView,
  MdHistory,
  MdHistoryEdu,
  MdLayers,
  MdLightbulb,
  MdList,
  MdListAlt,
  MdMic,
  MdMoreVert,
  MdNotifications,
  MdOutlineAdd,
  MdOutlineAddCircle,
  MdOutlineAnalytics,
  MdOutlineArchitecture,
  MdOutlineArrowRightAlt,
  MdOutlineAutoAwesome,
  MdOutlineAutoGraph,
  MdOutlineAutoStories,
  MdOutlineBolt,
  MdOutlineCalendarToday,
  MdOutlineCancelPresentation,
  MdOutlineChevronRight,
  MdOutlineDashboard,
  MdOutlineDelete,
  MdOutlineDownload,
  MdOutlineEdit,
  MdOutlineEditNote,
  MdOutlineGridView,
  MdOutlineHistory,
  MdOutlineHistoryEdu,
  MdOutlineLayers,
  MdOutlineLightbulb,
  MdOutlineList,
  MdOutlineListAlt,
  MdOutlineMic,
  MdOutlineMoreVert,
  MdOutlineNotifications,
  MdOutlinePlayCircle,
  MdOutlinePresentToAll,
  MdOutlinePsychology,
  MdOutlineQueryStats,
  MdOutlineReviews,
  MdOutlineSchedule,
  MdOutlineSchool,
  MdOutlineScience,
  MdOutlineSearch,
  MdOutlineSentimentDissatisfied,
  MdOutlineSentimentSatisfied,
  MdOutlineSentimentSatisfiedAlt,
  MdOutlineSentimentVeryDissatisfied,
  MdOutlineSentimentVerySatisfied,
  MdOutlineSettings,
  MdOutlineTimer,
  MdOutlineTrendingUp,
  MdPlayCircle,
  MdPresentToAll,
  MdPsychology,
  MdQueryStats,
  MdReviews,
  MdSchedule,
  MdSchool,
  MdScience,
  MdSearch,
  MdSentimentDissatisfied,
  MdSentimentSatisfied,
  MdSentimentSatisfiedAlt,
  MdSentimentVeryDissatisfied,
  MdSentimentVerySatisfied,
  MdSettings,
  MdTimer,
  MdTrendingUp,
} from "react-icons/md";

type Props = {
  name: string;
  className?: string;
  filled?: boolean;
};

/** [outline, filled] — SVG icons aligned with Material Design / your stitch mocks (no duplicate font + ligatures). */
const ICONS: Record<string, [IconType, IconType]> = {
  add: [MdOutlineAdd, MdAdd],
  add_circle: [MdOutlineAddCircle, MdAddCircle],
  analytics: [MdOutlineAnalytics, MdAnalytics],
  architecture: [MdOutlineArchitecture, MdArchitecture],
  arrow_right_alt: [MdOutlineArrowRightAlt, MdArrowRightAlt],
  auto_stories: [MdOutlineAutoStories, MdAutoStories],
  auto_awesome: [MdOutlineAutoAwesome, MdAutoAwesome],
  auto_graph: [MdOutlineAutoGraph, MdAutoGraph],
  bolt: [MdOutlineBolt, MdBolt],
  calendar_today: [MdOutlineCalendarToday, MdCalendarToday],
  cancel_presentation: [MdOutlineCancelPresentation, MdCancelPresentation],
  chevron_right: [MdOutlineChevronRight, MdChevronRight],
  dashboard: [MdOutlineDashboard, MdDashboard],
  delete: [MdOutlineDelete, MdDelete],
  download: [MdOutlineDownload, MdDownload],
  edit: [MdOutlineEdit, MdEdit],
  edit_note: [MdOutlineEditNote, MdEditNote],
  grid_view: [MdOutlineGridView, MdGridView],
  history: [MdOutlineHistory, MdHistory],
  history_edu: [MdOutlineHistoryEdu, MdHistoryEdu],
  layers: [MdOutlineLayers, MdLayers],
  lightbulb: [MdOutlineLightbulb, MdLightbulb],
  list: [MdOutlineList, MdList],
  list_alt: [MdOutlineListAlt, MdListAlt],
  mic: [MdOutlineMic, MdMic],
  more_vert: [MdOutlineMoreVert, MdMoreVert],
  notifications: [MdOutlineNotifications, MdNotifications],
  play_circle: [MdOutlinePlayCircle, MdPlayCircle],
  present_to_all: [MdOutlinePresentToAll, MdPresentToAll],
  psychology: [MdOutlinePsychology, MdPsychology],
  query_stats: [MdOutlineQueryStats, MdQueryStats],
  reviews: [MdOutlineReviews, MdReviews],
  schedule: [MdOutlineSchedule, MdSchedule],
  school: [MdOutlineSchool, MdSchool],
  science: [MdOutlineScience, MdScience],
  search: [MdOutlineSearch, MdSearch],
  sentiment_dissatisfied: [MdOutlineSentimentDissatisfied, MdSentimentDissatisfied],
  sentiment_satisfied: [MdOutlineSentimentSatisfied, MdSentimentSatisfied],
  sentiment_satisfied_alt: [MdOutlineSentimentSatisfiedAlt, MdSentimentSatisfiedAlt],
  sentiment_very_dissatisfied: [MdOutlineSentimentVeryDissatisfied, MdSentimentVeryDissatisfied],
  sentiment_very_satisfied: [MdOutlineSentimentVerySatisfied, MdSentimentVerySatisfied],
  settings: [MdOutlineSettings, MdSettings],
  timer: [MdOutlineTimer, MdTimer],
  trending_up: [MdOutlineTrendingUp, MdTrendingUp],
};

const FALLBACK: [IconType, IconType] = [MdOutlineSettings, MdSettings];

export function MaterialIcon({ name, className = "", filled = false }: Props) {
  const pair = ICONS[name] ?? FALLBACK;
  const Icon = filled ? pair[1] : pair[0];
  return <Icon className={className} aria-hidden />;
}
