import type { IconType } from "react-icons";
import {
  MdAdd,
  MdAddCircle,
  MdAnalytics,
  MdArchitecture,
  MdArrowBack,
  MdArrowRightAlt,
  MdAutoAwesome,
  MdAutoGraph,
  MdAutoStories,
  MdBolt,
  MdCalendarMonth,
  MdCalendarToday,
  MdCancelPresentation,
  MdCheckCircle,
  MdChevronLeft,
  MdChevronRight,
  MdClose,
  MdDashboard,
  MdDelete,
  MdDownload,
  MdEdit,
  MdEditNote,
  MdEvent,
  MdGridView,
  MdHistory,
  MdHistoryEdu,
  MdHome,
  MdLayers,
  MdLightbulb,
  MdList,
  MdListAlt,
  MdMic,
  MdInsights,
  MdMoreVert,
  MdNotifications,
  MdOutlineAdd,
  MdOutlineAddCircle,
  MdOutlineAnalytics,
  MdOutlineArchitecture,
  MdOutlineArrowBack,
  MdOutlineArrowRightAlt,
  MdOutlineAutoAwesome,
  MdOutlineAutoGraph,
  MdOutlineAutoStories,
  MdOutlineBolt,
  MdOutlineCalendarMonth,
  MdOutlineCalendarToday,
  MdOutlineCancelPresentation,
  MdOutlineCheckCircle,
  MdOutlineChevronLeft,
  MdOutlineChevronRight,
  MdOutlineClose,
  MdOutlineDashboard,
  MdOutlineDelete,
  MdOutlineDownload,
  MdOutlineEdit,
  MdOutlineEditNote,
  MdOutlineEvent,
  MdOutlineGridView,
  MdOutlineHistory,
  MdOutlineHistoryEdu,
  MdOutlineHome,
  MdOutlineLayers,
  MdOutlineLightbulb,
  MdOutlineList,
  MdOutlineListAlt,
  MdOutlineMic,
  MdOutlineInsights,
  MdOutlineMoreVert,
  MdOutlineNotifications,
  MdOutlinePause,
  MdOutlinePlayArrow,
  MdOutlinePlayCircle,
  MdOutlinePresentToAll,
  MdOutlinePrint,
  MdOutlinePsychology,
  MdOutlineQueryStats,
  MdOutlineRadioButtonUnchecked,
  MdOutlineRefresh,
  MdOutlineReviews,
  MdOutlineSchedule,
  MdOutlineSchool,
  MdOutlineScience,
  MdOutlineSearch,
  MdOutlineSentimentDissatisfied,
  MdOutlineSentimentSatisfied,
  MdOutlineSentimentSatisfiedAlt,
  MdOutlineSentimentVeryDissatisfied,
  MdOutlineSentimentVerySatisfied,
  MdOutlineSettings,
  MdOutlineSlideshow,
  MdOutlineStop,
  MdOutlineTimer,
  MdOutlineTrackChanges,
  MdOutlineTrendingUp,
  MdPause,
  MdPlayArrow,
  MdPlayCircle,
  MdPresentToAll,
  MdPrint,
  MdPsychology,
  MdQueryStats,
  MdRadioButtonUnchecked,
  MdRefresh,
  MdReviews,
  MdSchedule,
  MdSchool,
  MdScience,
  MdSearch,
  MdSentimentDissatisfied,
  MdSentimentSatisfied,
  MdSentimentSatisfiedAlt,
  MdSentimentVeryDissatisfied,
  MdSentimentVerySatisfied,
  MdSettings,
  MdSlideshow,
  MdStop,
  MdTimer,
  MdTrackChanges,
  MdTrendingUp,
} from "react-icons/md";

const ICONS = {
  add: [MdOutlineAdd, MdAdd],
  add_circle: [MdOutlineAddCircle, MdAddCircle],
  analytics: [MdOutlineAnalytics, MdAnalytics],
  architecture: [MdOutlineArchitecture, MdArchitecture],
  arrow_back: [MdOutlineArrowBack, MdArrowBack],
  arrow_right_alt: [MdOutlineArrowRightAlt, MdArrowRightAlt],
  auto_stories: [MdOutlineAutoStories, MdAutoStories],
  auto_awesome: [MdOutlineAutoAwesome, MdAutoAwesome],
  auto_graph: [MdOutlineAutoGraph, MdAutoGraph],
  bolt: [MdOutlineBolt, MdBolt],
  calendar_month: [MdOutlineCalendarMonth, MdCalendarMonth],
  calendar_today: [MdOutlineCalendarToday, MdCalendarToday],
  cancel_presentation: [MdOutlineCancelPresentation, MdCancelPresentation],
  check_circle: [MdOutlineCheckCircle, MdCheckCircle],
  chevron_left: [MdOutlineChevronLeft, MdChevronLeft],
  chevron_right: [MdOutlineChevronRight, MdChevronRight],
  close: [MdOutlineClose, MdClose],
  dashboard: [MdOutlineDashboard, MdDashboard],
  delete: [MdOutlineDelete, MdDelete],
  download: [MdOutlineDownload, MdDownload],
  edit: [MdOutlineEdit, MdEdit],
  edit_note: [MdOutlineEditNote, MdEditNote],
  event: [MdOutlineEvent, MdEvent],
  grid_view: [MdOutlineGridView, MdGridView],
  history: [MdOutlineHistory, MdHistory],
  history_edu: [MdOutlineHistoryEdu, MdHistoryEdu],
  home: [MdOutlineHome, MdHome],
  layers: [MdOutlineLayers, MdLayers],
  lightbulb: [MdOutlineLightbulb, MdLightbulb],
  list: [MdOutlineList, MdList],
  list_alt: [MdOutlineListAlt, MdListAlt],
  mic: [MdOutlineMic, MdMic],
  monitoring: [MdOutlineInsights, MdInsights],
  more_vert: [MdOutlineMoreVert, MdMoreVert],
  notifications: [MdOutlineNotifications, MdNotifications],
  pause: [MdOutlinePause, MdPause],
  play_arrow: [MdOutlinePlayArrow, MdPlayArrow],
  play_circle: [MdOutlinePlayCircle, MdPlayCircle],
  present_to_all: [MdOutlinePresentToAll, MdPresentToAll],
  print: [MdOutlinePrint, MdPrint],
  psychology: [MdOutlinePsychology, MdPsychology],
  query_stats: [MdOutlineQueryStats, MdQueryStats],
  radio_button_unchecked: [MdOutlineRadioButtonUnchecked, MdRadioButtonUnchecked],
  refresh: [MdOutlineRefresh, MdRefresh],
  reviews: [MdOutlineReviews, MdReviews],
  schedule: [MdOutlineSchedule, MdSchedule],
  school: [MdOutlineSchool, MdSchool],
  science: [MdOutlineScience, MdScience],
  search: [MdOutlineSearch, MdSearch],
  sentiment_dissatisfied: [MdOutlineSentimentDissatisfied, MdSentimentDissatisfied],
  sentiment_satisfied: [MdOutlineSentimentSatisfied, MdSentimentSatisfied],
  sentiment_satisfied_alt: [MdOutlineSentimentSatisfiedAlt, MdSentimentSatisfiedAlt],
  sentiment_very_dissatisfied: [
    MdOutlineSentimentVeryDissatisfied,
    MdSentimentVeryDissatisfied,
  ],
  sentiment_very_satisfied: [MdOutlineSentimentVerySatisfied, MdSentimentVerySatisfied],
  settings: [MdOutlineSettings, MdSettings],
  slideshow: [MdOutlineSlideshow, MdSlideshow],
  stop: [MdOutlineStop, MdStop],
  timer: [MdOutlineTimer, MdTimer],
  track_changes: [MdOutlineTrackChanges, MdTrackChanges],
  trending_up: [MdOutlineTrendingUp, MdTrendingUp],
} as const satisfies Record<string, [IconType, IconType]>;

export type IconName = keyof typeof ICONS;

type Props = {
  name: IconName;
  className?: string;
  filled?: boolean;
};

const FALLBACK: [IconType, IconType] = [MdOutlineSettings, MdSettings];

export function MaterialIcon({ name, className = "", filled = false }: Props) {
  const pair = ICONS[name] ?? FALLBACK;
  const Icon = filled ? pair[1] : pair[0];
  return <Icon className={className} aria-hidden />;
}
